<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.apache.logging.log4j</groupId>
    <artifactId>log4j</artifactId>
    <version>${revision}</version>
    <relativePath>../log4j-parent</relativePath>
  </parent>

  <artifactId>log4j-layout-template-yaml</artifactId>

  <name>Apache Log4j YAML Template Layout</name>
  <description>Apache Log4j Layout for producing YAML output that is structured according to a user-provided template.</description>

  <properties>
    <maven.test.skip>true</maven.test.skip>
    <bnd-module-name>org.apache.logging.log4j.layout.template.yaml</bnd-module-name>
    <bnd-extra-package-options>
      org.jctools.*;resolution:=optional,
    </bnd-extra-package-options>
    <Fragment-Host>org.apache.logging.log4j.core</Fragment-Host>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.apache.logging.log4j</groupId>
      <artifactId>log4j-core</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.logging.log4j</groupId>
      <artifactId>log4j-layout-template-structured</artifactId>
    </dependency>
    <dependency>
      <groupId>org.jctools</groupId>
      <artifactId>jctools-core</artifactId>
      <optional>true</optional>
    </dependency>
  </dependencies>
</project>
